name: Production Deploy

on:
  release:
    types: [published]

jobs:
  audit:
    uses: dascentral/reusable-workflows/.github/workflows/composer-audit.yml@c82d9b16ae70852a255ebb313bef9777c84b2368 # v0.5.0
    with:
      php-version: '8.4'

  tests:
    uses: dascentral/reusable-workflows/.github/workflows/laravel-tests.yml@c82d9b16ae70852a255ebb313bef9777c84b2368 # v0.5.0
    with:
      node-version: '22.20.0'
      php-version: '8.4'
      mysql-image: 'mysql:8.0'
    secrets:
      composer-auth: ${{ secrets.COMPOSER_AUTH }}

  deploy:
    needs: [tests, audit]
    uses: dascentral/reusable-workflows/.github/workflows/laravel-deploy.yml@c82d9b16ae70852a255ebb313bef9777c84b2368 # v0.5.0
    with:
      php-version: '8.4'
      node-version: '22.20.0'
      ssh-user: ${{ vars.SSH_USER }}
      ssh-host: ${{ vars.SSH_HOST }}
      destination-path: ${{ vars.DESTINATION_PATH }}
    secrets:
      composer-auth: ${{ secrets.COMPOSER_AUTH }}
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
